"use client";
import type { Metadata } from "next";
import { Titan_One, Lilita_One, Poppins } from "next/font/google";
import localFont from "next/font/local";
import { useEffect, useState } from "react";
import { loadConfig } from "@/lib/lineraClient";
import "./globals.css";

// Load the font
const titanOne = Titan_One({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

const lilitaOne = Lilita_One({
  weight: ["400"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lilita",
});

const satoshi = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "../public/fonts/Satoshi-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-satoshi",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [configLoaded, setConfigLoaded] = useState(false);

  useEffect(() => {
    loadConfig()
      .then(() => {
        setConfigLoaded(true);
        console.log("Linera config loaded successfully");
      })
      .catch((err) => {
        console.error("Failed to load Linera config:", err);
        setConfigLoaded(true); // Continue anyway
      });
  }, []);

  return (
    <html lang="en">
      <body
        className={`${titanOne.className} ${lilitaOne.variable} ${satoshi.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
